name: Wake FeedCord Poller

on:
  schedule:
    # Runs every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  wake-up:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Application URL
        run: |
          # Pinging the FQDN to wake the container from scale-to-zero
          curl -sL ${{ vars.CONTAINER_APP_URL }} > /dev/null
          echo "Application pinged at $(date)"
